version: '3'
services:
  db:
    container_name: db
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: 'json-file'
      options:
        max-size: '10M'
        max-file: '5'
